apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-vn1getmapping-deployment
  labels:
    app: docker-k8s-vn1getmapping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-vn1getmapping
  template:
    metadata:
      labels:
        app: docker-k8s-vn1getmapping
    spec:
      containers:
      - name: docker-k8s-vn1getmapping
        image: venunavat1989/vn-1-getmapping
        ports:
        - containerPort: 8080